---
- name: Manage EC2 instance state
  # We can write variables here too
  # vars:
  #   type: "t2.micro"
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    key_name: "himtest"
    vpc_subnet_id: subnet-00ca73fb0b4ceb383
    instance_type: "{{ type }}"
    security_groups:
      - launch-wizard-1
    region: ap-south-1
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    network:
      assign_public_ip: true
    image_id: ami-0e35ddab05955cf57
    tags:
      Name: test-node
      Environment: Testing
    state: "{{ ec2_state | default('present') }}"
